application:
  name: example s3 service
  minio:
    bucket:
      name: ${BUCKET_NAME:bucket-test}
    port: ${AWS_BUCKET_PORT:19000}
    secured: ${AWS_BUCKET_SECURED:false}
    access:
      name: ${AWS_ACCESS_KEY_ID:minio}
      secret: ${AWS_SECRET_ACCESS_KEY:minio123}
    url: ${AWS_BUCKET_URL:http://127.0.0.1}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
