version: '3.7'

services:
  minio:
    container_name: "minio"
    image: minio/minio
    ports:
#      - "${MINIO_API:-9000}"
#      - "${MINIO_UI:-9001}"
      - "19000:9000"
      - "19001:9001"
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=minio123"
    command: server /data --console-address ":9001"

  minio-client:
    container_name: "minio-client"
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/bucket-test;      
      exit 0;
      "